In [1]:
import sys
import os

repository_root_directory = os.path.dirname(os.getcwd())
rrd = "repository_root_directory:\t"
print(rrd, repository_root_directory)

if repository_root_directory not in sys.path:
    sys.path.append(repository_root_directory)
    print(rrd, "added to path")
else:  
    print(rrd, "already in path")

repository_root_directory:	 /teamspace/studios/this_studio/csc_461_fp
repository_root_directory:	 added to path


In [ ]:
# Reload the dataset and redo the optimization process
import pandas as pd
from sklearn.discriminant_analysis import StandardScaler
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import MinMaxScaler, Normalizer
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

# Reload dataset
file_path = '../_03_data_gtzan_features_labels_pca.xlsx'
dataset = pd.read_excel(file_path)

# Extract features and target
X = dataset.drop(columns=["Genre"])
y = dataset["Genre"]

# Normalize the features
scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)

# Split the dataset
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42, stratify=y)

# Define a range of values for k and weights
param_grid = {'n_neighbors': range(1, 21), 'weights': ['uniform', 'distance']}

# Perform grid search with cross-validation
grid_search = GridSearchCV(KNeighborsClassifier(), param_grid, cv=5, scoring='accuracy', n_jobs=-1)
grid_search.fit(X_train, y_train)

# Get the best parameters and score
best_params = grid_search.best_params_
best_score = grid_search.best_score_

# Train optimized KNN model
optimized_knn = grid_search.best_estimator_
optimized_knn.fit(X_train, y_train)

# Predict and evaluate the optimized model
y_pred_optimized = optimized_knn.predict(X_test)
optimized_accuracy = accuracy_score(y_test, y_pred_optimized)
optimized_classification_rep = classification_report(y_test, y_pred_optimized)
optimized_conf_matrix = confusion_matrix(y_test, y_pred_optimized)

#import ace_tools as tools; tools.display_dataframe_to_user(name="Optimized Confusion Matrix", dataframe=pd.DataFrame(optimized_conf_matrix))

print("Best parameters: ", best_params)
print("Best Cross validation training score: ", best_score)
print("Test Accuracy: ", optimized_accuracy) 
print(optimized_classification_rep)
print(optimized_conf_matrix)


Best parameters:  {'n_neighbors': 10, 'weights': 'distance'}
Best Cross validation training score:  0.5125
Test Accuracy:  0.51
              precision    recall  f1-score   support

           0       1.00      0.20      0.33        20
           1       0.94      0.85      0.89        20
           2       0.50      0.30      0.38        20
           3       0.47      0.35      0.40        20
           4       0.53      0.40      0.46        20
           5       0.33      0.75      0.46        20
           6       0.53      0.90      0.67        20
           7       0.48      0.70      0.57        20
           8       0.44      0.20      0.28        20
           9       0.47      0.45      0.46        20

    accuracy                           0.51       200
   macro avg       0.57      0.51      0.49       200
weighted avg       0.57      0.51      0.49       200

[[ 4  0  2  1  0  7  2  0  1  3]
 [ 0 17  0  0  0  2  0  0  1  0]
 [ 0  0  6  1  0  8  0  2  1  2]
 [ 0  1  1  7 

/home/zeus/miniconda3/envs/cloudspace/lib/python3.9/site-packages/numpy/ma/core.py:2820: RuntimeWarning: invalid value encountered in cast
  _data = np.array(data, dtype=dtype, copy=copy,


In [3]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV

# Define the parameter grid for hyperparameter tuning
param_grid = {
    'C': [0.01, 0.1, 1, 10, 100],  # Regularization strength (inverse of regularization parameter)
    'solver': ['lbfgs', 'newton-cg', 'saga']  # Different solvers for optimization
}

# Perform grid search with cross-validation
grid_search_logreg = GridSearchCV(
    LogisticRegression(multi_class='multinomial', max_iter=1000, random_state=42),
    param_grid,
    cv=5,
    scoring='accuracy',
    n_jobs=-1
)
grid_search_logreg.fit(X_train, y_train)

# Get the best parameters and corresponding score
best_params_logreg = grid_search_logreg.best_params_
best_score_logreg = grid_search_logreg.best_score_

# Train the optimized model on the training set
optimized_logreg = grid_search_logreg.best_estimator_
optimized_logreg.fit(X_train, y_train)

# Predict on the test set with the optimized model
y_pred_optimized_logreg = optimized_logreg.predict(X_test)

# Evaluate the optimized model
optimized_accuracy_logreg = accuracy_score(y_test, y_pred_optimized_logreg)
optimized_classification_rep_logreg = classification_report(y_test, y_pred_optimized_logreg)
optimized_conf_matrix_logreg = confusion_matrix(y_test, y_pred_optimized_logreg)

# tools.display_dataframe_to_user(
#     name="Optimized Logistic Regression Confusion Matrix",
#     dataframe=pd.DataFrame(optimized_conf_matrix_logreg)
# )

print(best_params_logreg)
print(best_score_logreg)
print(optimized_accuracy_logreg)
print(optimized_classification_rep_logreg)


/home/zeus/miniconda3/envs/cloudspace/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/home/zeus/miniconda3/envs/cloudspace/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/home/zeus/miniconda3/envs/cloudspace/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/home/zeus/miniconda3/envs/cloudspace/lib/python3.9/site-packages/s

{'C': 10, 'solver': 'saga'}
0.6287499999999999
0.675
              precision    recall  f1-score   support

           0       0.71      0.75      0.73        20
           1       0.86      0.90      0.88        20
           2       0.40      0.30      0.34        20
           3       0.73      0.55      0.63        20
           4       0.77      0.85      0.81        20
           5       0.79      0.75      0.77        20
           6       0.78      0.90      0.84        20
           7       0.59      0.85      0.69        20
           8       0.48      0.60      0.53        20
           9       0.60      0.30      0.40        20

    accuracy                           0.68       200
   macro avg       0.67      0.67      0.66       200
weighted avg       0.67      0.68      0.66       200



In [5]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset

# Convert data to PyTorch tensors
X_train_tensor = torch.tensor(X_train, dtype=torch.float32)
y_train_tensor = torch.tensor(y_train.values, dtype=torch.long)
X_test_tensor = torch.tensor(X_test, dtype=torch.float32)
y_test_tensor = torch.tensor(y_test.values, dtype=torch.long)

# Create DataLoader for batching
train_dataset = TensorDataset(X_train_tensor, y_train_tensor)
test_dataset = TensorDataset(X_test_tensor, y_test_tensor)
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=False)

# Define the Neural Network model
class NeuralNetwork(nn.Module):
    def __init__(self, input_size, hidden_size, num_classes):
        super(NeuralNetwork, self).__init__()
        self.fc1 = nn.Linear(input_size, hidden_size)
        self.relu = nn.ReLU()
        self.fc2 = nn.Linear(hidden_size, num_classes)
    
    def forward(self, x):
        x = self.fc1(x)
        x = self.relu(x)
        x = self.fc2(x)
        return x

# Model parameters
input_size = X_train.shape[1]
hidden_size = 64  # Number of neurons in the hidden layer
num_classes = len(y.unique())

# Initialize the model, loss function, and optimizer
model = NeuralNetwork(input_size, hidden_size, num_classes)
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.0001)

# Training loop
num_epochs = 4000
for epoch in range(num_epochs):
    model.train()
    for X_batch, y_batch in train_loader:
        # Forward pass
        outputs = model(X_batch)
        loss = criterion(outputs, y_batch)
        
        # Backward pass and optimization
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
    
    print(f"Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.4f}")

# Evaluate the model
model.eval()
correct = 0
total = 0
with torch.no_grad():
    for X_batch, y_batch in test_loader:
        outputs = model(X_batch)
        _, predicted = torch.max(outputs, 1)
        total += y_batch.size(0)
        correct += (predicted == y_batch).sum().item()

test_accuracy = correct / total

test_accuracy


Epoch [1/4000], Loss: 2.2972
Epoch [2/4000], Loss: 2.3029
Epoch [3/4000], Loss: 2.2803
Epoch [4/4000], Loss: 2.2984
Epoch [5/4000], Loss: 2.2813
Epoch [6/4000], Loss: 2.2784
Epoch [7/4000], Loss: 2.2711
Epoch [8/4000], Loss: 2.2879
Epoch [9/4000], Loss: 2.2675
Epoch [10/4000], Loss: 2.2597
Epoch [11/4000], Loss: 2.2442
Epoch [12/4000], Loss: 2.2488
Epoch [13/4000], Loss: 2.2384
Epoch [14/4000], Loss: 2.2500
Epoch [15/4000], Loss: 2.2504
Epoch [16/4000], Loss: 2.2003
Epoch [17/4000], Loss: 2.2291
Epoch [18/4000], Loss: 2.1909
Epoch [19/4000], Loss: 2.2070
Epoch [20/4000], Loss: 2.1722
Epoch [21/4000], Loss: 2.1860
Epoch [22/4000], Loss: 2.1564
Epoch [23/4000], Loss: 2.1233
Epoch [24/4000], Loss: 2.1871
Epoch [25/4000], Loss: 2.0800
Epoch [26/4000], Loss: 2.1250
Epoch [27/4000], Loss: 2.1343
Epoch [28/4000], Loss: 2.0847
Epoch [29/4000], Loss: 2.0837
Epoch [30/4000], Loss: 2.1375
Epoch [31/4000], Loss: 2.0687
Epoch [32/4000], Loss: 2.0549
Epoch [33/4000], Loss: 2.0638
Epoch [34/4000], Lo

0.64