In [5]:
import sys
import os

repository_root_directory = os.path.dirname(os.getcwd())
rrd = "repository_root_directory:\t"
print(rrd, repository_root_directory)

if repository_root_directory not in sys.path:
    sys.path.append(repository_root_directory)
    print(rrd, "added to path")
else:  
    print(rrd, "already in path")

repository_root_directory:	 c:\Users\cengl\Documents\CSC 461\New code\csc_461_fp-main USE THIS ONE\csc_461_fp-main
repository_root_directory:	 already in path


In [9]:
# Reload the dataset and redo the optimization process
import pandas as pd
from sklearn.discriminant_analysis import StandardScaler
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import MinMaxScaler, Normalizer
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from joblib import dump

# Reload dataset
file_path = '../_03_data_gtzan_features_labels_pca.xlsx'
dataset = pd.read_excel(file_path)

# Extract features and target
X = dataset.drop(columns=["Genre"])
y = dataset["Genre"]

# Normalize the features
scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)

# Split the dataset
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42, stratify=y)

# Define a range of values for k and weights
param_grid = {'n_neighbors': range(1, 21), 'weights': ['uniform', 'distance']}

# Perform grid search with cross-validation
grid_search = GridSearchCV(KNeighborsClassifier(), param_grid, cv=5, scoring='accuracy', n_jobs=-1)
grid_search.fit(X_train, y_train)

# Get the best parameters and score
best_params = grid_search.best_params_
best_score = grid_search.best_score_

# Train optimized KNN model
optimized_knn = grid_search.best_estimator_
optimized_knn.fit(X_train, y_train)

# Predict and evaluate the optimized model
y_pred_optimized = optimized_knn.predict(X_test)
optimized_accuracy = accuracy_score(y_test, y_pred_optimized)
optimized_classification_rep = classification_report(y_test, y_pred_optimized)
optimized_conf_matrix = confusion_matrix(y_test, y_pred_optimized)

#import ace_tools as tools; tools.display_dataframe_to_user(name="Optimized Confusion Matrix", dataframe=pd.DataFrame(optimized_conf_matrix))

print("Best parameters: ", best_params)
print("Best Cross validation training score: ", best_score)
print("Test Accuracy: ", optimized_accuracy) 
print(optimized_classification_rep)
print(optimized_conf_matrix)

dump(optimized_knn, 'knn_model.joblib')

Best parameters:  {'n_neighbors': 5, 'weights': 'distance'}
Best Cross validation training score:  0.5425
Test Accuracy:  0.52
              precision    recall  f1-score   support

           0       0.88      0.35      0.50        20
           1       0.72      0.90      0.80        20
           2       0.31      0.20      0.24        20
           3       0.57      0.40      0.47        20
           4       0.50      0.35      0.41        20
           5       0.38      0.60      0.46        20
           6       0.55      0.90      0.68        20
           7       0.44      0.60      0.51        20
           8       0.71      0.25      0.37        20
           9       0.48      0.65      0.55        20

    accuracy                           0.52       200
   macro avg       0.55      0.52      0.50       200
weighted avg       0.55      0.52      0.50       200

[[ 7  2  1  1  0  4  2  0  0  3]
 [ 0 18  1  0  0  0  0  0  0  1]
 [ 1  0  4  2  0  8  0  4  0  1]
 [ 0  1  0  8  

['knn_model.joblib']

In [10]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV
from joblib import dump

# Define the parameter grid for hyperparameter tuning
param_grid = {
    'C': [0.01, 0.1, 1, 10, 100],  # Regularization strength (inverse of regularization parameter)
    'solver': ['lbfgs', 'newton-cg', 'saga']  # Different solvers for optimization
}

# Perform grid search with cross-validation
grid_search_logreg = GridSearchCV(
    LogisticRegression(multi_class='multinomial', max_iter=1000, random_state=42),
    param_grid,
    cv=5,
    scoring='accuracy',
    n_jobs=-1
)
grid_search_logreg.fit(X_train, y_train)

# Get the best parameters and corresponding score
best_params_logreg = grid_search_logreg.best_params_
best_score_logreg = grid_search_logreg.best_score_

# Train the optimized model on the training set
optimized_logreg = grid_search_logreg.best_estimator_
optimized_logreg.fit(X_train, y_train)

# Predict on the test set with the optimized model
y_pred_optimized_logreg = optimized_logreg.predict(X_test)

# Evaluate the optimized model
optimized_accuracy_logreg = accuracy_score(y_test, y_pred_optimized_logreg)
optimized_classification_rep_logreg = classification_report(y_test, y_pred_optimized_logreg)
optimized_conf_matrix_logreg = confusion_matrix(y_test, y_pred_optimized_logreg)

# tools.display_dataframe_to_user(
#     name="Optimized Logistic Regression Confusion Matrix",
#     dataframe=pd.DataFrame(optimized_conf_matrix_logreg)
# )

print(best_params_logreg)
print(best_score_logreg)
print(optimized_accuracy_logreg)
print(optimized_classification_rep_logreg)

dump(optimized_logreg, 'lrModel.joblib')

c:\Users\cengl\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
c:\Users\cengl\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(


{'C': 10, 'solver': 'saga'}
0.6287499999999999
0.675
              precision    recall  f1-score   support

           0       0.71      0.75      0.73        20
           1       0.86      0.90      0.88        20
           2       0.40      0.30      0.34        20
           3       0.73      0.55      0.63        20
           4       0.77      0.85      0.81        20
           5       0.79      0.75      0.77        20
           6       0.78      0.90      0.84        20
           7       0.59      0.85      0.69        20
           8       0.48      0.60      0.53        20
           9       0.60      0.30      0.40        20

    accuracy                           0.68       200
   macro avg       0.67      0.67      0.66       200
weighted avg       0.67      0.68      0.66       200



['lrModel.joblib']

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset

# Convert data to PyTorch tensors
X_train_tensor = torch.tensor(X_train, dtype=torch.float32)
y_train_tensor = torch.tensor(y_train.values, dtype=torch.long)
X_test_tensor = torch.tensor(X_test, dtype=torch.float32)
y_test_tensor = torch.tensor(y_test.values, dtype=torch.long)

# Create DataLoader for batching
train_dataset = TensorDataset(X_train_tensor, y_train_tensor)
test_dataset = TensorDataset(X_test_tensor, y_test_tensor)
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=False)

# Define the Neural Network model
class NeuralNetwork(nn.Module):
    def __init__(self, input_size, hidden_size, num_classes):
        super(NeuralNetwork, self).__init__()
        self.fc1 = nn.Linear(input_size, hidden_size)
        self.relu = nn.ReLU()
        self.fc2 = nn.Linear(hidden_size, num_classes)
    
    def forward(self, x):
        x = self.fc1(x)
        x = self.relu(x)
        x = self.fc2(x)
        return x

# Model parameters
input_size = X_train.shape[1]
hidden_size = 64  # Number of neurons in the hidden layer
num_classes = len(y.unique())

# Initialize the model, loss function, and optimizer
model = NeuralNetwork(input_size, hidden_size, num_classes)
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.0001)

# Training loop
num_epochs = 4000
for epoch in range(num_epochs):
    model.train()
    for X_batch, y_batch in train_loader:
        # Forward pass
        outputs = model(X_batch)
        loss = criterion(outputs, y_batch)
        
        # Backward pass and optimization
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
    
    print(f"Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.4f}")

# Evaluate the model
model.eval()
correct = 0
total = 0
with torch.no_grad():
    for X_batch, y_batch in test_loader:
        outputs = model(X_batch)
        _, predicted = torch.max(outputs, 1)
        total += y_batch.size(0)
        correct += (predicted == y_batch).sum().item()

test_accuracy = correct / total

test_accuracy

#save the model for later use
torch.save(model.state_dict(), 'nn_model.pth')


Epoch [1/4000], Loss: 2.2954
Epoch [2/4000], Loss: 2.2734
Epoch [3/4000], Loss: 2.2874
Epoch [4/4000], Loss: 2.2877
Epoch [5/4000], Loss: 2.2702
Epoch [6/4000], Loss: 2.2596
Epoch [7/4000], Loss: 2.2473
Epoch [8/4000], Loss: 2.2613
Epoch [9/4000], Loss: 2.2437
Epoch [10/4000], Loss: 2.2759
Epoch [11/4000], Loss: 2.2139
Epoch [12/4000], Loss: 2.2373
Epoch [13/4000], Loss: 2.2383
Epoch [14/4000], Loss: 2.2184
Epoch [15/4000], Loss: 2.2132
Epoch [16/4000], Loss: 2.2005
Epoch [17/4000], Loss: 2.2188
Epoch [18/4000], Loss: 2.2239
Epoch [19/4000], Loss: 2.1928
Epoch [20/4000], Loss: 2.1878
Epoch [21/4000], Loss: 2.1554
Epoch [22/4000], Loss: 2.1868
Epoch [23/4000], Loss: 2.1438
Epoch [24/4000], Loss: 2.1447
Epoch [25/4000], Loss: 2.1478
Epoch [26/4000], Loss: 2.1199
Epoch [27/4000], Loss: 2.0835
Epoch [28/4000], Loss: 2.1123
Epoch [29/4000], Loss: 2.0730
Epoch [30/4000], Loss: 2.0849
Epoch [31/4000], Loss: 2.0809
Epoch [32/4000], Loss: 2.0067
Epoch [33/4000], Loss: 2.0237
Epoch [34/4000], Lo

0.655